# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_31bfdc556f31de46109316f11e4e4e5dba4ec2d1

# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

# Analysis settings
sonar.sources=client/src,controllers,models,routes,middlewares,helpers,config

# Exclusions
sonar.exclusions=**/*.test.js,**/*.spec.js,**/node_modules/**,**/coverage/**,**/__mocks__/**

# Test coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.js,**/*.spec.js,**/setupTests.js
